engines:
  pep8:
    enabled: true
    checks:
        E501:
            enabled: false
        E402:
            enabled: false
ratings:
    paths:
        - "**.py"
exclude_paths:
    - versioneer.py
    - bluepyopt/_version.py
    - docs/source/conf.py
    - bluepyopt/tests
    - examples
